
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'SLR'

_lr_signature = '\x94\xd8\xb2\x1d\x8a\x8dM\xe1\xbc\xbe\x98[\xd8\xf0P\xc3'

_lr_action_items = {'BRABRA':([28,3,15,22,6,14,5,21,9,24,8,0,23,7,18,26,10,17,],[-11,-9,-12,1,-5,-6,1,-18,-4,-19,-13,1,-17,-8,-10,-14,-7,1,]),'$':([8,7,9,10,2,18,26,3,13,4,28,14,5,15,6,],[-13,-8,-4,-7,-1,-10,-14,-9,-3,0,-11,-6,-2,-12,-5,]),'EQUALS':([26,18,17,10,24,16,9,7,8,23,0,6,22,15,21,14,28,5,3,],[-14,-10,7,-7,-19,19,-4,-8,-13,-17,7,7,7,-12,-18,-6,-11,7,-9,]),'ELSE':([26,18,11,17,10,24,9,1,7,8,23,0,6,22,15,5,21,14,28,3,19,],[-14,-10,16,10,-7,-19,-4,12,-8,-13,-17,10,10,10,-12,10,-18,-6,-11,-9,25,]),'KET':([20,28,12,27,22,15,21,16,24,23,7,11,18,26,10,25,],[26,-11,17,-16,-15,-12,-18,18,-19,-17,-8,15,-10,-14,-7,28,]),'BRA':([28,6,3,22,15,21,14,5,9,24,23,8,7,18,0,26,17,10,],[-11,-5,-9,11,-12,-18,-6,11,-4,-19,-17,-13,-8,-10,11,-14,11,-7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_action[(_x,_k)] = _y
del _lr_action_items

_lr_goto_items = {'termlist':([5,0,],[13,2,]),'tagcontentlist':([22,17,],[27,20,]),'hint':([17,0,5,22,],[21,3,3,21,]),'text':([0,],[4,]),'tagcontent':([22,17,],[22,22,]),'else':([6,22,5,17,0,],[6,23,6,23,6,]),'tag':([5,0,17,22,],[8,8,24,24,]),'term':([0,5,],[5,5,]),'elselist':([6,0,5,],[14,9,9,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_goto[(_x,_k)] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('text',1,'p_text','Lexer.py',72),
  ('termlist',1,'p_termlist_1','Lexer.py',76),
  ('termlist',2,'p_termlist_2','Lexer.py',80),
  ('term',1,'p_term_1','Lexer.py',84),
  ('elselist',1,'p_elselist_1','Lexer.py',88),
  ('elselist',2,'p_elselist_2','Lexer.py',92),
  ('else',1,'p_else_1','Lexer.py',96),
  ('else',1,'p_else_2','Lexer.py',100),
  ('term',1,'p_term_2','Lexer.py',104),
  ('hint',3,'p_hint_1','Lexer.py',108),
  ('hint',5,'p_hint_2','Lexer.py',112),
  ('hint',2,'p_hint_3','Lexer.py',116),
  ('term',1,'p_term_3','Lexer.py',121),
  ('tag',5,'p_tag_1','Lexer.py',125),
  ('tagcontentlist',1,'p_tagcontentlist_1','Lexer.py',129),
  ('tagcontentlist',2,'p_tagcontentlist_2','Lexer.py',133),
  ('tagcontent',1,'p_tagcontent_1','Lexer.py',137),
  ('tagcontent',1,'p_tagcontent_2','Lexer.py',141),
  ('tagcontent',1,'p_tagcontent_3','Lexer.py',145),
]
